service: hh-ai-interaction
plugins:
  - serverless-webpack
custom:
  webpack:
    includeModules: true
    packager: "npm"
    excludeFiles: src/**/*.test.js
provider:
  name: aws
  runtime: nodejs18.x
  timeout: 29
  versionFunctions: false
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    # Secrets Manager secret names (secure approach)
    OPENAI_SECRET_NAME: "healthhub/${self:provider.stage}/openai-credentials"
    S3_BUCKET: hh-${self:provider.stage}-${aws:accountId}-ai-interaction
    AI_INTERACTION_TABLE: ${self:service}-${self:provider.stage}-ai-interactions
    
    # Fallback environment variables (for backward compatibility during migration)
    OPEN_AI_KEY: "your-openai-api-key-here"
    ASSISTANT_ID: "asst_kNQua24M16TEWPFwV9eNR1dL"
  iamRoleStatements:
    # DynamoDB permissions
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.AI_INTERACTION_TABLE}"
    
    # S3 permissions
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
        - s3:DeleteObject
        - s3:ListBucket
      Resource:
        - "arn:aws:s3:::${self:provider.environment.S3_BUCKET}"
        - "arn:aws:s3:::${self:provider.environment.S3_BUCKET}/*"
    
    # AWS AI services permissions
    - Effect: Allow
      Action:
        - polly:SynthesizeSpeech
        - translate:TranslateText
      Resource: "*"
    
    # CRITICAL: Secrets Manager permissions
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
        - secretsmanager:DescribeSecret
      Resource: 
        - "arn:aws:secretsmanager:${self:provider.region}:*:secret:healthhub/${self:provider.stage}/openai-credentials*"
        - "arn:aws:secretsmanager:${self:provider.region}:*:secret:healthhub/dev/openai-credentials*"
    
    # NEW: Secrets Manager permissions
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
        - secretsmanager:DescribeSecret
      Resource: 
        - "arn:aws:secretsmanager:${self:provider.region}:*:secret:healthhub/${self:provider.stage}/openai-credentials*"
    - Effect: Allow
      Action:
        - kms:Decrypt
        - kms:DescribeKey
      Resource: "*"
      Condition:
        StringEquals:
          "kms:ViaService": "secretsmanager.${self:provider.region}.amazonaws.com"
  httpApi:
    id:
      "Fn::ImportValue": HH-HttpAPI-${sls:stage}
functions:
  # Dashboard-compatible AI interaction handlers
  create:
    handler: src/handlers/aiInteractionDashboard.create
    events:
      - httpApi:
          path: /ai-interactions
          method: post

  get:
    handler: src/handlers/aiInteractionDashboard.get
    events:
      - httpApi:
          path: /ai-interactions/{id}
          method: get

  update:
    handler: src/handlers/aiInteractionDashboard.update
    events:
      - httpApi:
          path: /ai-interactions/{id}
          method: put

  delete:
    handler: src/handlers/aiInteractionDashboard.remove
    events:
      - httpApi:
          path: /ai-interactions/{id}
          method: delete

  list:
    handler: src/handlers/aiInteractionDashboard.list
    events:
      - httpApi:
          path: /ai-interactions
          method: get

  processVirtualAssistant:
    handler: src/handlers/aiInteractionDashboard.virtualAssistant
    events:
      - httpApi:
          path: /ai-interactions/virtual-assistant
          method: post

  convertTextToSpeech:
    handler: src/handlers/aiInteractionDashboard.textToSpeech
    events:
      - httpApi:
          path: /ai-interactions/text-to-speech
          method: post

resources:
  Resources:
    AIInteractionTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.AI_INTERACTION_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
          - AttributeName: interactionType
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: UserIdIndex
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
              - AttributeName: interactionType
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
    AIInteractionBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.S3_BUCKET}
        OwnershipControls:
          Rules:
            - ObjectOwnership: ObjectWriter
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false
        AccessControl: Private
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - "*"
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              AllowedOrigins:
                - "*"
              MaxAge: 3000
