name: HealthHub Rollback

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to rollback'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - development
      reason:
        description: 'Reason for rollback'
        required: true
        type: string

env:
  AWS_REGION: us-east-1
  NODE_VERSION: '18'

jobs:
  rollback:
    name: Rollback Deployment
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          role-duration-seconds: 3600
          role-session-name: HealthHub-Rollback-${{ github.event.inputs.environment }}

      - name: Install dependencies
        run: |
          cd health-hub-backend
          npm install

      - name: Rollback backend services
        run: |
          cd health-hub-backend
          STAGE=${{ github.event.inputs.environment == 'production' && 'production' || 'dev' }}
          npx @serverless/compose remove --stage $STAGE
          echo "Backend services rolled back for $STAGE"

      - name: Notify rollback completion
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: |
            {
              text: "🚨 HealthHub Rollback Completed",
              attachments: [{
                color: "warning",
                fields: [{
                  title: "Environment",
                  value: "${{ github.event.inputs.environment }}",
                  short: true
                }, {
                  title: "Reason",
                  value: "${{ github.event.inputs.reason }}",
                  short: true
                }, {
                  title: "Triggered by",
                  value: "${{ github.actor }}",
                  short: true
                }]
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
